// Generated by https://quicktype.io

class Categoria {
  int id;
  String name;
  String slug;
  int parent;
  String description;
  String display;
  dynamic image;
  int menuOrder;
  int count;
  Links links;

  Categoria({
    this.id,
    this.name,
    this.slug,
    this.parent,
    this.description,
    this.display,
    this.image,
    this.menuOrder,
    this.count,
    this.links,
  });

  Categoria.fromJSonList(Map<String,dynamic> jsonCat){
    this.id          = jsonCat['id'];
    this.name        = jsonCat['name'];
    this.slug        = jsonCat['slug'];
    this.parent      = jsonCat['parent'];
    this.description = jsonCat['description'];
    this.display     = jsonCat['display'];
    this.image       = jsonCat['image'];
    this.menuOrder   = jsonCat['menu_order'];
    this.count       = jsonCat['count'];
    this.links       = jsonCat['_links'];
  }
}

class ImageClass {
  int id;
  String dateCreated;
  String dateCreatedGmt;
  String dateModified;
  String dateModifiedGmt;
  String src;
  String name;
  String alt;

  ImageClass({
    this.id,
    this.dateCreated,
    this.dateCreatedGmt,
    this.dateModified,
    this.dateModifiedGmt,
    this.src,
    this.name,
    this.alt,
  });
}

class Links {
  List<Collection> self;
  List<Collection> collection;
  List<Collection> up;

  Links({
    this.self,
    this.collection,
    this.up,
  });
}

class Collection {
  String href;

  Collection({
    this.href,
  });
}
